name: Progress Consistency
on:
  pull_request:
    branches: [ main ]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check ops/progress.yaml and PROJECT.md consistency
        shell: bash
        run: |
          set -euo pipefail
          BASE_SHA='${{ github.event.pull_request.base.sha }}'
          HEAD_SHA='${{ github.event.pull_request.head.sha }}'
          echo "Base SHA: $BASE_SHA"
          echo "Head SHA: $HEAD_SHA"

          # fetch the exact SHAs with minimal history to ensure diff works
          git fetch --no-tags --depth=1 origin "$BASE_SHA" "$HEAD_SHA"

          echo "Changed files (base..head):"
          CHANGED=$(git diff --name-only "$BASE_SHA".."$HEAD_SHA")
          echo "$CHANGED"

          if echo "$CHANGED" | grep -q '^ops/progress.yaml$'; then
            if ! echo "$CHANGED" | grep -q '^PROJECT.md$'; then
              echo "::error::ops/progress.yaml changed but PROJECT.md not updated. Keep single-source of truth."
              exit 1
            fi
          fi

          echo "Consistency check passed."
